apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sng97o3bc-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:eff60ebec5baa1f60344b9fba5946b233b71fec9@sha256:77eaa5ecc0fb774f7f9cf65e68d7d2a0dd72552e27679f5b6f8bb1014d269c9c
          name: container-image
